### PR TITLE
fix: build without sound

### LINKED ISSUE #281: v2.7.0 Fails to build with Rust-1.96.0-beta.7
Hi,

Trying to update the NetBSD package but, I cannot build release locally.

Is this a known issue?
I know ... building with non-stable Rust is probably not something you support but, 1.96 will be out in just a few days.

```
   Compiling chess-tui v2.7.0 (/usr/pkgsrc/wip/chess-tui/work/chess-tui-2.7.0)
error[E0599]: no method named `toggle_help_popup` found for mutable reference `&mut App` in the current scope
  --> src/app/menu.rs:92:41
   |
92 |             MainMenuItems::Help => self.toggle_help_popup(),
   |                                         ^^^^^^^^^^^^^^^^^ method not found in `&mut App`
   |
help: one of the expressions' fields has a method of the same name
   |
92 |             MainMenuItems::Help => self.ui_state.toggle_help_popup(),
   |                                         +++++++++

For more information about this error, try `rustc --explain E0599`.
error: could not compile `chess-tui` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

The same happens on macOS when building with `--no-default-features`. It builds fine with _default features_

Thing is ... I don't want `alsa`, neither on NetBSD nor, on macOS

### PR DESCRIPTION
**Pull request by thomas-mauran**
# Fix the build without --no-default-features

## Description

Fixes #281 

## How Has This Been Tested?

Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by thomas-mauran** [comment]
Hello @0323pin if you wanna double check that this branch builds on your side too before I release

**Comment by 0323pin** [comment]
> Hello @0323pin if you wanna double check that this branch builds on your side too before I release

Sure, no problem.

It builds just fine with one single warning:
```
warning: constant `SAMPLE_RATE` is never used

--> src/sound.rs:10:7

|

10 | const SAMPLE_RATE: NonZero<u32> = match NonZero::new(44100) {

| ^^^^^^^^^^^

|

note: the lint level is defined here

--> src/lib.rs:1:9

|

1 | #![warn(dead_code)]

| ^^^^^^^^^



warning: `chess-tui` (lib) generated 1 warning
```

But, this was expected as the code is not being used.

**Comment by thomas-mauran** [comment]
Removed the warning, thank you @0323pin !

**Comment by 0323pin** [comment]
Update [merged](http://mail-index.netbsd.org/pkgsrc-changes/2026/05/21/msg346615.html)

**Comment by thomas-mauran** [comment]
> Update [merged](http://mail-index.netbsd.org/pkgsrc-changes/2026/05/21/msg346615.html)

Thank you very much again for taking the time to maintain chess-tui up to date !!!
Means a lot
