### ISSUE TITLE
v2.7.0 Fails to build with Rust-1.96.0-beta.7

### ISSUE THREAD

**Issue by 0323pin** [thomas-mauran/chess-tui#281]
Hi,

Trying to update the NetBSD package but, I cannot build release locally.

Is this a known issue?
I know ... building with non-stable Rust is probably not something you support but, 1.96 will be out in just a few days.

```
   Compiling chess-tui v2.7.0 (/usr/pkgsrc/wip/chess-tui/work/chess-tui-2.7.0)
error[E0599]: no method named `toggle_help_popup` found for mutable reference `&mut App` in the current scope
  --> src/app/menu.rs:92:41
   |
92 |             MainMenuItems::Help => self.toggle_help_popup(),
   |                                         ^^^^^^^^^^^^^^^^^ method not found in `&mut App`
   |
help: one of the expressions' fields has a method of the same name
   |
92 |             MainMenuItems::Help => self.ui_state.toggle_help_popup(),
   |                                         +++++++++

For more information about this error, try `rustc --explain E0599`.
error: could not compile `chess-tui` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

The same happens on macOS when building with `--no-default-features`. It builds fine with _default features_

Thing is ... I don't want `alsa`, neither on NetBSD nor, on macOS

**Comment by thomas-mauran** [comment]
Hello @0323pin didn't notice this bug thanks for reporting it fixing it right now and releasing a 2.7.1 !

**Comment by 0323pin** [comment]
Thanks!
